import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[#000] h-[100vh] flex justify-center items-center">
        <h1 className="text-[#fff] text-3xl text-teal-500 font-bold">
          Next.js Boiler Plate
        </h1>
      </main>
    </div>
  )
}
